// eTime Jewellers — shared product catalogue data
// Used by catalog.html and product.html

const PRODUCTS = [
  {
    id: 1,
    name: "Classic Solitaire Engagement Ring",
    shortName: "Classic Solitaire Ring",
    category: "Engagement Rings",
    subcategory: "rings",
    material: "Sterling Silver",
    stone: "Cubic Zirconia",
    price: "R1,850",
    priceNote: "",
    image: "./IMG_7336.JPEG",
    description: "A timeless classic — this elegant solitaire ring features a brilliant round-cut cubic zirconia set in polished sterling silver. Clean, minimal, and forever in style. Perfect as an engagement ring or a meaningful gift for someone special.",
    details: [
      "Sterling silver 925",
      "Round brilliant-cut cubic zirconia",
      "Rhodium plated for lasting shine",
      "Available in ring sizes 5–10",
    ],
    inStock: true,
  },
  {
    id: 2,
    name: "Halo Princess-Cut Ring",
    shortName: "Halo Diamond Ring",
    category: "Engagement Rings",
    subcategory: "rings",
    material: "Sterling Silver",
    stone: "CZ Halo Setting",
    price: "R2,450",
    priceNote: "",
    image: "./IMG_7303.JPEG",
    description: "Make a statement with this stunning halo engagement ring. A princess-cut centre stone is surrounded by a sparkling border of round CZ stones, all set in beautifully polished sterling silver.",
    details: [
      "Sterling silver 925",
      "Princess-cut centre CZ with halo surround",
      "Rhodium plated",
      "Available in ring sizes 5–10",
    ],
    inStock: true,
  },
  {
    id: 3,
    name: "Six-Prong Solitaire Ring",
    shortName: "Six-Prong Solitaire",
    category: "Silver Jewellery",
    subcategory: "rings",
    material: "Sterling Silver",
    stone: "Cubic Zirconia",
    price: "R1,950",
    priceNote: "",
    image: "./IMG_7211.JPEG",
    description: "An elevated take on the classic solitaire. Six precisely crafted prongs cradle a brilliant-cut CZ stone, maximising light reflection and giving this ring a distinctly luxurious, fine-jewellery look.",
    details: [
      "Sterling silver 925",
      "Round brilliant CZ in six-prong setting",
      "Rhodium plated for lasting lustre",
      "Available in ring sizes 5–10",
    ],
    inStock: true,
  },
  {
    id: 4,
    name: "Gold Onyx Signet Ring",
    shortName: "Gold Signet Ring",
    category: "Gold Jewellery",
    subcategory: "rings",
    material: "Gold (by arrangement)",
    stone: "Black Onyx",
    price: "POA",
    priceNote: "A deposit is required. Contact us for pricing.",
    image: "./63840bdb-ffc0-451a-a321-4d3228bd0237.JPEG",
    description: "A bold, masculine statement piece. This classic signet ring features a polished black onyx inlay set in a substantial gold band — understated luxury at its finest. Gold pieces are available by arrangement with a deposit.",
    details: [
      "9ct or 18ct gold (your choice)",
      "Black onyx cushion-shaped inlay",
      "Available in various sizes",
      "Deposit required — contact us to order",
    ],
    inStock: true,
  },
  {
    id: 5,
    name: "Custom Name Necklace",
    shortName: "Name Necklace",
    category: "Custom Jewellery",
    subcategory: "necklaces",
    material: "Gold-Plated Silver",
    stone: "N/A",
    price: "From R750",
    priceNote: "Price varies by name length and chain length.",
    image: "./1fb571c5-30da-43d2-9225-6f4a891b191e.JPEG",
    description: "Wear your name — or someone special's — close to your heart. Our handcrafted name necklaces are made to order in beautiful cursive script on gold-plated 925 silver. A perfect personalised gift that means something.",
    details: [
      "Gold-plated 925 silver",
      "Cursive script styling",
      "Various chain lengths available",
      "Personalised — allow 3–5 working days",
    ],
    inStock: true,
  },
  {
    id: 6,
    name: "Amethyst Silver Ring",
    shortName: "Amethyst Ring",
    category: "Silver Jewellery",
    subcategory: "rings",
    material: "Sterling Silver",
    stone: "Natural Amethyst",
    price: "R1,250",
    priceNote: "",
    image: "./8919454A-AC05-4D94-A828-A211C9264A24.JPEG",
    description: "A delicate sterling silver ring set with a genuine faceted amethyst. The soft violet hue of the amethyst makes this piece both feminine and distinctive — beautiful for everyday wear or a special occasion.",
    details: [
      "Sterling silver 925",
      "Genuine faceted amethyst stone",
      "Four-prong claw setting",
      "Available in ring sizes 5–9",
    ],
    inStock: true,
  },
  {
    id: 7,
    name: "Diamond Cluster Cocktail Ring",
    shortName: "Diamond Cluster Ring",
    category: "Engagement Rings",
    subcategory: "rings",
    material: "Sterling Silver",
    stone: "CZ Starburst Cluster",
    price: "R3,200",
    priceNote: "",
    image: "./1.JPEG",
    description: "Turn heads with this show-stopping cluster ring. A large champagne-toned centre CZ is surrounded by a dazzling starburst halo of smaller round stones — bold, beautiful, and unmistakably luxurious.",
    details: [
      "Sterling silver 925",
      "Champagne CZ centre with white CZ halo",
      "Starburst cluster design",
      "Available in ring sizes 5–10",
    ],
    inStock: true,
  },
  {
    id: 8,
    name: "Rose Gold Diamond Eternity Band",
    shortName: "Rose Gold Eternity Band",
    category: "Custom Jewellery",
    subcategory: "rings",
    material: "Rose Gold & Yellow Gold",
    stone: "CZ / Diamond (your choice)",
    price: "POA",
    priceNote: "Bespoke piece — deposit required. Contact us for a quote.",
    image: "./BEC65AF0-430C-47D5-AB9F-E103B84AF41E.JPEG",
    description: "A breathtaking bespoke creation: rose gold and yellow gold bands interlocked and studded with brilliant stones. This eternity-style ring is a testament to our master craftsmanship — made exactly to your specifications.",
    details: [
      "Rose gold & yellow gold combination",
      "Full pave CZ or diamond setting",
      "Custom ring sizing",
      "Made to order — allow 2–3 weeks",
    ],
    inStock: true,
  },
  {
    id: 9,
    name: "Classic Gold Solitaire Engagement Ring",
    shortName: "Gold Solitaire Ring",
    category: "Engagement Rings",
    subcategory: "rings",
    material: "Gold",
    stone: "Diamond or CZ",
    price: "POA",
    priceNote: "Gold with diamond requires a deposit. CZ option also available.",
    image: "./IMG_4836.JPEG",
    description: "The quintessential engagement ring — a single dazzling stone on a slim gold band. Simple. Elegant. Timeless. We craft this in 9ct or 18ct gold with your choice of stone, sized and finished exactly to your preference.",
    details: [
      "9ct or 18ct gold",
      "Diamond or cubic zirconia stone",
      "Slim band design",
      "Custom sizing and stone selection",
    ],
    inStock: true,
  },
];
